### ISSUE TITLE
Include a `stack.yaml` for easier compiling with known working versions

### ISSUE THREAD

**Issue by bwbaugh** [jtdaugherty/tart#1]
Would there be any objection to having a `stack.yaml` file to make it simpler to compile this project with `stack install`?

This worked for me:

```yaml
resolver: lts-9.0
packages:
- .
extra-deps:
- brick-0.23
- vty-5.17
- word-wrap-0.4.1
```

----

I generated the above with `stack init --solver --resolver=lts-9.0` since using `--resolver=nightly` is crashing right now with:

```bash
$ stack init --solver --resolver=nightly
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- tart.cabal

Selected resolver: nightly-2017-08-14
Selected resolver: nightly-2017-08-14
Downloaded nightly-2017-08-14 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```
